source:         .
destination:    ./_site
auto:           true
server:         true
exclude:        Icon.png, fabfile.py, config.rb, sass, CNAME, CNAME.template, README, Rakefile
permalink:      pretty
pygments:       true
